#if !canImport(ObjectiveC)
import XCTest

extension HelloWorldTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HelloWorldTests = [
        ("testHelloWorldSucceeds", testHelloWorldSucceeds),
    ]
}

extension InboundEmailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InboundEmailTests = [
        ("testInboundEmailChannelFoundAndNotified", testInboundEmailChannelFoundAndNotified),
        ("testInboundEmailChannelNotFound", testInboundEmailChannelNotFound),
        ("testLowercasedInboundEmailChannelFoundAndNotified", testLowercasedInboundEmailChannelFoundAndNotified),
    ]
}

extension RegistrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegistrationTests = [
        ("testBasicRegistration", testBasicRegistration),
        ("testRegistrationConflictForExistingEmail", testRegistrationConflictForExistingEmail),
        ("testRegistrationWithDeviceAndEmail", testRegistrationWithDeviceAndEmail),
        ("testRegistrationWithDevice", testRegistrationWithDevice),
        ("testRegistrationWithoutDeviceButEmail", testRegistrationWithoutDeviceButEmail),
    ]
}

extension SendMessageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SendMessageTests = [
        ("testPublicNotifyNotFound", testPublicNotifyNotFound),
        ("testPublicNotify", testPublicNotify),
        ("testPublicNotifyWithLowercasedNotifyKey", testPublicNotifyWithLowercasedNotifyKey),
    ]
}

extension SubscriptionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubscriptionTests = [
        ("testPublicNotify", testPublicNotify),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HelloWorldTests.__allTests__HelloWorldTests),
        testCase(InboundEmailTests.__allTests__InboundEmailTests),
        testCase(RegistrationTests.__allTests__RegistrationTests),
        testCase(SendMessageTests.__allTests__SendMessageTests),
        testCase(SubscriptionTests.__allTests__SubscriptionTests),
    ]
}
#endif
